name: Procesadores de Lenguajes. Itinerario de ComputaciÃ³n. ETSII. ULL
markdown: redcarpet
pygments: true
exclude:  [ Gemfile, Gemfile.lock, Procfile, vendor, gems]
# Liquid-LaTeX plugin
liquid_latex:
  debug: false
  density: 150
  usepackages: pst-all,pst-3dplot
  output_directory: /res/latex
  latex_cmd: "latex -interaction=nonstopmode $texfile &> /dev/null"
  dvips_cmd: "dvips -E $dvifile -o $epsfile &> /dev/null"
  convert_cmd: "convert -density $density $epsfile $pngfile &> /dev/null"
  temp_filename: "latex_temp"
